/**
 * Generated GraphQL Types
 *
 * This file would typically be generated by GraphQL Code Generator
 * For POC-3, we define types manually based on the schema
 */

import type { GraphQLContext } from '../context';

// Type definitions based on schema
export type Resolvers<Context = GraphQLContext> = {
  DateTime?: DateTimeScalarConfig;
  JSON?: JsonScalarConfig;
  Query?: QueryResolvers<Context>;
  Mutation?: MutationResolvers<Context>;
  Subscription?: SubscriptionResolvers<Context>;
  User?: UserResolvers<Context>;
  AuthResponse?: AuthResponseResolvers<Context>;
  Payment?: PaymentResolvers<Context>;
  PaymentConnection?: PaymentConnectionResolvers<Context>;
  PaymentEdge?: PaymentEdgeResolvers<Context>;
  PageInfo?: PageInfoResolvers<Context>;
  Profile?: ProfileResolvers<Context>;
  AuditLog?: AuditLogResolvers<Context>;
  SystemConfig?: SystemConfigResolvers<Context>;
};

// Scalar types
export interface DateTimeScalarConfig {
  parseValue?: (value: unknown) => Date;
  serialize?: (value: unknown) => string;
}

export interface JsonScalarConfig {
  parseValue?: (value: unknown) => unknown;
  serialize?: (value: unknown) => unknown;
}

// Resolver types (simplified - would be generated in production)
export type QueryResolvers<Context = GraphQLContext> = {
  me?: (parent: unknown, args: unknown, context: Context) => Promise<unknown>;
  payment?: (
    parent: unknown,
    args: { id: string },
    context: Context
  ) => Promise<unknown | null>;
  payments?: (
    parent: unknown,
    args: { input?: PaginationInput },
    context: Context
  ) => Promise<unknown>;
  profile?: (
    parent: unknown,
    args: unknown,
    context: Context
  ) => Promise<unknown | null>;
  users?: (
    parent: unknown,
    args: { input?: PaginationInput },
    context: Context
  ) => Promise<unknown[]>;
  user?: (
    parent: unknown,
    args: { id: string },
    context: Context
  ) => Promise<unknown | null>;
  auditLogs?: (
    parent: unknown,
    args: { input?: PaginationInput },
    context: Context
  ) => Promise<unknown[]>;
  systemConfig?: (
    parent: unknown,
    args: { key: string },
    context: Context
  ) => Promise<unknown | null>;
};

export type MutationResolvers<Context = GraphQLContext> = {
  login?: (
    parent: unknown,
    args: { input: LoginInput },
    context: Context
  ) => Promise<unknown>;
  register?: (
    parent: unknown,
    args: { input: RegisterInput },
    context: Context
  ) => Promise<unknown>;
  logout?: (
    parent: unknown,
    args: unknown,
    context: Context
  ) => Promise<boolean>;
  refreshToken?: (
    parent: unknown,
    args: { refreshToken: string },
    context: Context
  ) => Promise<unknown>;
  createPayment?: (
    parent: unknown,
    args: { input: CreatePaymentInput },
    context: Context
  ) => Promise<unknown>;
  updatePayment?: (
    parent: unknown,
    args: { id: string; input: UpdatePaymentInput },
    context: Context
  ) => Promise<unknown>;
  deletePayment?: (
    parent: unknown,
    args: { id: string },
    context: Context
  ) => Promise<boolean>;
  updateProfile?: (
    parent: unknown,
    args: { input: UpdateProfileInput },
    context: Context
  ) => Promise<unknown>;
  updateUserRole?: (
    parent: unknown,
    args: { id: string; role: string },
    context: Context
  ) => Promise<unknown>;
  updateSystemConfig?: (
    parent: unknown,
    args: { key: string; value: unknown },
    context: Context
  ) => Promise<unknown>;
};

export type SubscriptionResolvers<Context = GraphQLContext> = {
  paymentUpdated?: (
    parent: unknown,
    args: { userId: string },
    context: Context
  ) => AsyncIterable<unknown>;
  userUpdated?: (
    parent: unknown,
    args: unknown,
    context: Context
  ) => AsyncIterable<unknown>;
};

// Input types
export interface PaginationInput {
  first?: number;
  after?: string;
  last?: number;
  before?: string;
}

export interface LoginInput {
  email: string;
  password: string;
}

export interface RegisterInput {
  email: string;
  password: string;
  name: string;
}

export interface CreatePaymentInput {
  amount: number;
  currency: string;
  type: string;
  description?: string;
  metadata?: unknown;
}

export interface UpdatePaymentInput {
  status?: string;
  description?: string;
  metadata?: unknown;
}

export interface UpdateProfileInput {
  firstName?: string;
  lastName?: string;
  phone?: string;
  address?: string;
  city?: string;
  country?: string;
  avatar?: string;
  preferences?: unknown;
}

// Type resolvers (simplified)
export type UserResolvers<_Context = GraphQLContext> = Record<string, unknown>;
export type AuthResponseResolvers<_Context = GraphQLContext> = Record<
  string,
  unknown
>;
export type PaymentResolvers<_Context = GraphQLContext> = Record<
  string,
  unknown
>;
export type PaymentConnectionResolvers<_Context = GraphQLContext> = Record<
  string,
  unknown
>;
export type PaymentEdgeResolvers<_Context = GraphQLContext> = Record<
  string,
  unknown
>;
export type PageInfoResolvers<_Context = GraphQLContext> = Record<
  string,
  unknown
>;
export type ProfileResolvers<_Context = GraphQLContext> = Record<
  string,
  unknown
>;
export type AuditLogResolvers<_Context = GraphQLContext> = Record<
  string,
  unknown
>;
export type SystemConfigResolvers<_Context = GraphQLContext> = Record<
  string,
  unknown
>;
