/**
 * Auto-generated SRI hashes for Module Federation remotes
 * Generated at: 2026-02-12T09:01:04.623Z
 * Algorithm: sha384
 *
 * DO NOT EDIT - This file is auto-generated by scripts/security/generate-sri-hashes.js
 * Run 'pnpm build:remotes:sri' to regenerate
 */

export const SRI_ALGORITHM = 'sha384' as const;

export const SRI_GENERATED_AT = '2026-02-12T09:01:04.623Z' as const;

export const REMOTE_INTEGRITY_HASHES = {
  'authMfe': 'sha384-v1dOXIn6XEye1nyABbjJghdy2X2Gqo+/QoY083ydvG7Qb/6d6rG8XM2hP6n6Q/1Q',
  'paymentsMfe': 'sha384-b4VGfnIPWhYYzurC8bWfmo/ORtXtSpJS4xzxlwqVz6u/lNJe9Tl+Jh4Qn0rBU+J/',
  'adminMfe': 'sha384-coT3QkQx2+I5nVWY4UFqy6TaJViDJ4LkNcz3A8EnhOlAJPWpgATJ1xb0HKUtyBLR',
  'profileMfe': 'sha384-j2YQNO8nUkm4527DETzotWJVtRUGmz5jmD6ylTdAKu3vkeTdr4alEzxJCbcfxwhP'
} as const;

export type RemoteName = keyof typeof REMOTE_INTEGRITY_HASHES;

/**
 * Get the SRI hash for a remote MFE
 * @param remoteName - Name of the remote (e.g., 'authMfe')
 * @returns SRI hash string or undefined if not found
 */
export function getRemoteIntegrityHash(remoteName: string): string | undefined {
  if (remoteName in REMOTE_INTEGRITY_HASHES) {
    return REMOTE_INTEGRITY_HASHES[remoteName as RemoteName];
  }
  return undefined;
}
